language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - export JENA_VERSION=3.4.0
  - export JENA_HOME=apache-jena-$JENA_VERSION
  - wget http://www.apache.org/dist/jena/binaries/$JENA_HOME.tar.gz
  - tar zxf apache-jena-3.4.0.tar.gz
  - export FUSEKI_HOME=apache-jena-fuseki-$JENA_VERSION
  - wget http://www.apache.org/dist/jena/binaries/$FUSEKI_HOME.tar.gz
  - tar xzf $FUSEKI_HOME.tar.gz
  - export PATH=$PATH:$PWD/$JENA_HOME/bin:$PWD/$FUSEKI_HOME:$PWD/$FUSEKI_HOME/bin
install:
  - pip install coveralls pep8 pep257
script:
  - pep8 --ignore=E501 *.py
  - pep257 *.py
  - python test_bteko2bf_sparql.py
